### PR TITLE
coala.css: Change default list style to disc

### PR DESCRIPTION
**Pull request by hemangsk**
Closes https://github.com/coala/coalaCSS/issues/2

### CODE REVIEW

**Comment by hemangsk** [comment]
@rultor merge

**Comment by meetmangukiya** [comment]
discs don't make any sense for order lists

**Comment by hemangsk** [comment]
But this is unordered : https://github.com/coala/coalaCSS/blob/master/coala.css#L624

**Comment by meetmangukiya** [comment]
Hmm.. but my ordered lists are rendered as unordered :/

**Pull request merged**
