### PR TITLE
coalaOnline: Style the repository linting input box

### PR DESCRIPTION
**Pull request by sd5869**
@yukiisbored I have edited the commit message and also merged it properly. Please review.

### CODE REVIEW

**Comment by SanketDG** [comment]
@sd5869 please squash your commit messages https://asciinema.org/a/11269

**Comment by sd5869** [comment]
@SanketDG Thanks for the link I have done it please review and let me know if there are any improvements to be made.

**Comment by SanketDG** [comment]
@sd5869 your commits are not squashed. Please check again

**Comment by sd5869** [comment]
@SanketDG Please check now.

**Comment by yukiisbored** [comment]
Euhm, your commit message doesn't follow our commit message guidelines.
See coala.io/commit for reference.

**Comment by sd5869** [comment]
I read the guide could you tell me what must be the commit message please

**Comment by hemangsk** [comment]
@sd5869 commit message must contain file name in commit shortlog, 
presently file name is inside commit body instead of commit shortlog.

**Comment by jayvdb** [comment]
Fixes coala/landing-frontend#188

**Comment by jayvdb** [comment]
Commit message problem not fixed.
Closing due to inactivity.

**Pull request closed without merging**
